logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace


spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: lhb64961077
        url: jdbc:mysql://localhost:3306/gymbo?characterEncoding=UTF-8&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    servlet:
        multipart:
            maxFileSize: 10MB
            maxRequestSize: 20MB
    mail:
        host: smtp.naver.com
        port: 465
        username: ghqls654@naver.com
        password: lbs64961077
        properties:
            mail.smtp.auth: true
            mail.smtp.ssl.enable: true
            mail.smtp.ssl.trust: smtp.naver.com
    redis:
        host: localhost
        port: 6379

payment:
    toss:
        test_client_api_key : test_ck_DnyRpQWGrNa7onxBlEWLVKwv1M9E
        test_secrete_api_key : test_sk_4yKeq5bgrp2M7oylRvDp3GX0lzW6
        success_url : "http://localhost:8080/v1/payments/toss/success"
        fail_url: "http://localhost:8080/v1/payments/toss/fail"

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
server:
    port: 8080
